services:
  autopilot:
    class: Inspectioneering\AutopilotBundle\Service\AutopilotManager
    public: true
    arguments:
      - '%autopilot.api_key%'

  Inspectioneering\AutopilotBundle\Service\AutopilotManager: '@autopilot'